apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.compute.name }}
  namespace: {{ .Values.general.namespace }}
  labels:
    app: {{ .Values.compute.app }}
spec:
  selector:
    app: {{ .Values.compute.app }}
  ports:
  - name: {{ .Values.compute.grpc_portname }}
    port: 50051
    targetPort: 50051
    protocol: TCP
