apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000M"
  labels:
    app: {{ .Values.compute.app }}
  name: {{ .Values.compute.name }}
  namespace: {{ .Values.general.namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.compute.host }}
    secretName: {{ .Values.general.ssl_cert_secret }}
  rules:
  - host: {{ .Values.compute.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.compute.name }}
          servicePort: {{ .Values.compute.grpc_portname }}