apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/proxy-body-size: "10M"
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: {{ .Values.artemis.app }}
  name: {{ .Values.artemis.name }}
  namespace: {{ .Values.general.namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.artemis.flask_host }}
    secretName: {{ .Values.general.ssl_cert_secret }}
  rules:
  - host: {{ .Values.artemis.flask_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.artemis.name }}
          servicePort: 80
